// ============================================================================
// extract-seed.mjs
// Extracts the demo dataset from the app's own defaultDB() and emits a Postgres
// seed migration (00002_seed.sql). Guarantees the live DB matches the demo.
// Plaintext passwords are STRIPPED — auth users are created later via
// scripts/seed-users.mjs using Supabase Auth (server-side bcrypt).
// ============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const APP = path.join(__dirname, '..', 'reference', 'PilatesStudioApp.html');
const OUT = path.join(__dirname, '..', 'supabase', 'migrations', '00002_seed.sql');

const html = readFileSync(APP, 'utf8');
const scriptMatch = html.match(/<script[^>]*>([\s\S]*?)<\/script>/);
if (!scriptMatch) throw new Error('No <script> block found');
const js = scriptMatch[1];

// Extract only the self-contained defaultDB() function via brace matching.
const fnStart = js.indexOf('function defaultDB()');
if (fnStart < 0) throw new Error('defaultDB not found');
const openIdx = js.indexOf('{', fnStart);
let depth = 0, endIdx = -1;
for (let i = openIdx; i < js.length; i++) {
  if (js[i] === '{') depth++;
  else if (js[i] === '}') { depth--; if (depth === 0) { endIdx = i; break; } }
}
if (endIdx < 0) throw new Error('defaultDB braces unbalanced');
const fnText = js.slice(fnStart, endIdx + 1);

const ctx = vm.createContext({ Date });
vm.runInContext(fnText, ctx);
const db = vm.runInContext('defaultDB()', ctx);

// ---------- helpers ----------
const q = v => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'string') return "'" + v.replace(/'/g, "''") + "'";
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  return "'" + JSON.stringify(v).replace(/'/g, "''") + "'";
};
const pgArray = arr => "'{" + (arr || []).map(x => '"' + String(x).replace(/"/g, '""') + '"').join(',') + "}'::text[]";
const pgTags = tags => (tags && tags.length ? pgArray(tags) : "'{}'::text[]");
const esc = s => String(s ?? '').replace(/'/g, "''");

// Instructor name -> id map (classes store instructor *names* in the demo).
const instrIdByName = {};
for (const i of db.instructors) instrIdByName[i.name] = i.id;

const lines = [];
lines.push('-- ============================================================================');
lines.push('-- Pilates Studio App — demo dataset (migration 00002)');
lines.push('-- Generated by scripts/extract-seed.mjs from the app\'s own defaultDB().');
lines.push('-- No plaintext passwords: auth users are provisioned separately via');
lines.push('-- scripts/seed-users.mjs against Supabase Auth.');
lines.push('-- ============================================================================');
lines.push('BEGIN;');
lines.push('');
lines.push('TRUNCATE public.student_injuries, public.student_milestones, public.student_notes,');
lines.push('         public.class_notes, public.instructor_feedback, public.attendance,');
lines.push('         public.demo_sessions, public.classes, public.students, public.instructors,');
lines.push('         public.studio_settings CASCADE;');
lines.push('');

// --- studio_settings (single row) ---
const settings = db.settings;
lines.push('INSERT INTO public.studio_settings (id, data) VALUES (1, ' + q(settings) + ');');
lines.push('');

// --- instructors (password, loginId stripped/renamed) ---
lines.push('-- instructors');
for (const i of db.instructors) {
  const cols = ['id','name','specialization','certification','experience','email','phone','photo','active','date_joined','bio','availability','permissions','rating','login_id'];
  const vals = [
    q(i.id), q(i.name), q(i.specialization), q(i.certification),
    String(i.experience ?? 3), q(i.email), q(i.phone), q(i.photo),
    String(i.active ?? true), q(i.dateJoined), q(i.bio),
    q(i.availability ?? {}), q(i.permissions ?? {}), String(i.rating ?? 4.0),
    q(i.loginId ?? null)
  ];
  lines.push('INSERT INTO public.instructors (' + cols.join(', ') + ') VALUES (' + vals.join(', ') + ');');
}
lines.push('');

// --- students ---
lines.push('-- students');
for (const s of db.students) {
  const cols = ['id','name','phone','email','gender','emergency','active','level','level_progress','enrolled_classes','enrolled_demos'];
  const vals = [
    q(s.id), q(s.name), q(s.phone), q(s.email), q(s.gender), q(s.emergency),
    String(s.active ?? true), q(s.level ?? 'beginner'),
    q(s.levelProgress ?? { beginner: 0, intermediate: 0, expert: 0 }),
    pgArray(s.enrolledClasses), pgArray(s.enrolledDemos)
  ];
  lines.push('INSERT INTO public.students (' + cols.join(', ') + ') VALUES (' + vals.join(', ') + ');');
}
lines.push('');

// --- classes (instructor name -> id) ---
lines.push('-- classes');
for (const c of db.classes) {
  const iid = instrIdByName[c.instructor] || null;
  const cols = ['id','type','level','date','time','duration','max_students','status','instructor','enrolled','waitlist'];
  const vals = [
    q(c.id), q(c.type), q(c.level ?? 'beginner'), q(c.date), q(c.time),
    String(c.duration ?? 60), String(c.maxStudents ?? 15), q(c.status ?? 'active'),
    q(iid), pgArray(c.enrolled), pgArray(c.waitlist)
  ];
  lines.push('INSERT INTO public.classes (' + cols.join(', ') + ') VALUES (' + vals.join(', ') + ');');
}
lines.push('');

// --- demo sessions ---
lines.push('-- demo sessions');
for (const d of db.demoSessions) {
  const cols = ['id','date','time','duration','max_students','enrolled'];
  const vals = [q(d.id), q(d.date), q(d.time), String(d.duration ?? 45), String(d.maxStudents ?? 5), pgArray(d.enrolled)];
  lines.push('INSERT INTO public.demo_sessions (' + cols.join(', ') + ') VALUES (' + vals.join(', ') + ');');
}
lines.push('');

// --- attendance ---
lines.push('-- attendance');
for (const [classId, map] of Object.entries(db.attendance || {})) {
  for (const [studentId, status] of Object.entries(map)) {
    lines.push(`INSERT INTO public.attendance (class_id, student_id, status) VALUES (${q(classId)}, ${q(studentId)}, ${q(status)});`);
  }
}
lines.push('');

// --- class notes ---
lines.push('-- class notes');
for (const [classId, smap] of Object.entries(db.classNotes || {})) {
  for (const [studentId, notes] of Object.entries(smap)) {
    for (const n of notes) {
      const ts = n.timestamp ? q(n.timestamp) : 'now()';
      lines.push(`INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES (${q(classId)}, ${q(studentId)}, ${q(n.text)}, ${pgTags(n.tags)}, ${ts});`);
    }
  }
}
lines.push('');

// --- student notes ---
lines.push('-- student notes');
for (const n of db.studentNotes) {
  const cols = ['id','student_id','text','date','added_by'];
  const vals = [q(n.id), q(n.studentId), q(n.text), q(n.date), q(n.addedBy)];
  lines.push('INSERT INTO public.student_notes (' + cols.join(', ') + ') VALUES (' + vals.join(', ') + ');');
}
lines.push('');

// --- milestones ---
lines.push('-- milestones');
for (const m of db.studentMilestones) {
  const cols = ['id','student_id','title','description','date','achieved'];
  const vals = [q(m.id), q(m.studentId), q(m.title), q(m.description), q(m.date), String(m.achieved ?? true)];
  lines.push('INSERT INTO public.student_milestones (' + cols.join(', ') + ') VALUES (' + vals.join(', ') + ');');
}
lines.push('');

// --- injuries ---
lines.push('-- injuries');
for (const j of db.studentInjuries) {
  const cols = ['id','student_id','body_part','severity','notes','modification','date','resolved'];
  const vals = [q(j.id), q(j.studentId), q(j.bodyPart), q(j.severity), q(j.notes), q(j.modification), q(j.date), String(j.resolved ?? false)];
  lines.push('INSERT INTO public.student_injuries (' + cols.join(', ') + ') VALUES (' + vals.join(', ') + ');');
}
lines.push('');

// --- instructor feedback ---
lines.push('-- instructor feedback');
for (const f of db.instructorFeedback) {
  const cols = ['instructor_id','student_id','rating','comment','date'];
  const vals = [q(f.instructorId), q(f.studentId), String(f.rating), q(f.comment), q(f.date)];
  lines.push('INSERT INTO public.instructor_feedback (' + cols.join(', ') + ') VALUES (' + vals.join(', ') + ');');
}
lines.push('');

lines.push('COMMIT;');
lines.push('');

writeFileSync(OUT, lines.join('\n'));
console.log('Wrote ' + OUT);
console.log('  instructors: ' + db.instructors.length);
console.log('  students:    ' + db.students.length);
console.log('  classes:     ' + db.classes.length);
console.log('  classNotes rows: ' + Object.values(db.classNotes || {}).reduce((a, m) => a + Object.values(m).reduce((b, arr) => b + arr.length, 0), 0));
