// ============================================================================
// seed-users.mjs — Provisions demo auth accounts on a Supabase project.
//
//   Requires scripts/.env.local with:
//     SUPABASE_URL=...
//     SUPABASE_SERVICE_ROLE_KEY=...   (SECRET — server-side only)
//
//   Run: node scripts/seed-users.mjs
//
// Behaviour:
//   * Reads scripts/accounts.json (generated by generate-accounts.mjs) so the
//     documented passwords are exactly the ones provisioned.
//   * Creates auth.users via the Admin API (passwords bcrypt-hashed by
//     Supabase Auth — plaintext exists only in accounts.json/CREDENTIALS.txt).
//   * Inserts a public.profiles row per user (role: admin | instructor | student).
//   * Links instructors.profile_user_id / students.profile_user_id.
//   * Idempotent-ish: skips users whose email already exists.
// ============================================================================
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@supabase/supabase-js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ---- env ---------------------------------------------------------------
const envFile = path.join(__dirname, '.env.local');
const env = {};
if (existsSync(envFile)) {
  for (const line of readFileSync(envFile, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}
const SUPABASE_URL = process.env.SUPABASE_URL || env.SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('Missing SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY. Create scripts/.env.local (see scripts/.env.local.example).');
  process.exit(1);
}

// ---- accounts (fixed passwords from generate-accounts.mjs) ----------------
const accountsFile = path.join(__dirname, 'accounts.json');
if (!existsSync(accountsFile)) {
  console.error('Missing scripts/accounts.json. Run: node scripts/generate-accounts.mjs');
  process.exit(1);
}
const saved = JSON.parse(readFileSync(accountsFile, 'utf8'));
const accounts = saved.map(a => ({
  key: a.key,
  email: a.email,
  displayName: a.displayName,
  role: a.role,
  password: a.password,
  meta: { loginId: a.loginId, studentId: a.key },
  instructorId: a.role === 'instructor' ? a.loginId : undefined,
  studentId: a.role === 'student' ? a.key : undefined,
}));

// ---- create accounts ----------------------------------------------------
const sb = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { autoRefreshToken: false, persistSession: false } });

const created = [];
const skipped = [];

for (const a of accounts) {
  const { password } = a;
  let user;
  try {
    const { data, error } = await sb.auth.admin.createUser({
      email: a.email,
      password,
      email_confirm: true,
      user_metadata: { displayName: a.displayName, role: a.role, ...a.meta },
    });
    if (error) {
      if (String(error.message).toLowerCase().includes('already')) {
        skipped.push(a.key);
        continue;
      }
      throw error;
    }
    user = data.user;
  } catch (err) {
    console.error(`[skip] ${a.key} (${a.email}): ${err.message}`);
    skipped.push(a.key);
    continue;
  }

  const { error: profileError } = await sb.from('profiles').upsert({
    id: user.id,
    role: a.role,
    display_name: a.displayName,
    email: a.email,
    meta: a.meta,
  }, { onConflict: 'id' });
  if (profileError) {
    console.error(`[warn] ${a.key}: profile upsert failed: ${profileError.message}`);
  }

  if (a.instructorId) {
    await sb.from('instructors').update({ profile_user_id: user.id }).eq('id', a.instructorId);
  }
  if (a.studentId) {
    await sb.from('students').update({ profile_user_id: user.id }).eq('id', a.studentId);
  }

  created.push({ key: a.key, email: a.email, role: a.role, password, displayName: a.displayName });
  console.log(`[ok] ${a.key.padEnd(8)} ${a.email.padEnd(34)} role=${a.role.padEnd(10)} password=${password}`);
}

// ---- persist credentials ------------------------------------------------
const credLines = [
  '===========================================================================',
  ' PILATES STUDIO APP — DEMO ACCOUNT CREDENTIALS (generated ' + new Date().toISOString() + ')',
  ' Store securely. These are bcrypt-hashed in Supabase Auth; plaintext exists',
  ' only here and in this file. Delete CREDENTIALS.txt after noting them down.',
  '===========================================================================',
  '',
];
for (const c of created) {
  credLines.push(`${c.role.toUpperCase().padEnd(11)} | ${c.displayName.padEnd(16)} | ${c.email.padEnd(34)} | ${c.password}`);
}
if (skipped.length) credLines.push('', `Skipped (email already exists): ${skipped.join(', ')}`);
credLines.push('');

const out = path.join(__dirname, '..', 'CREDENTIALS.txt');
writeFileSync(out, credLines.join('\n'));
console.log(`\nCredentials written to ${out} (gitignored).`);
console.log(`Created ${created.length}, skipped ${skipped.length}.`);
