-- ============================================================================
-- Pilates Studio App — demo dataset (migration 00002)
-- Generated by scripts/extract-seed.mjs from the app's own defaultDB().
-- No plaintext passwords: auth users are provisioned separately via
-- scripts/seed-users.mjs against Supabase Auth.
-- ============================================================================
BEGIN;

TRUNCATE public.student_injuries, public.student_milestones, public.student_notes,
         public.class_notes, public.instructor_feedback, public.attendance,
         public.demo_sessions, public.classes, public.students, public.instructors,
         public.studio_settings CASCADE;

INSERT INTO public.studio_settings (id, data) VALUES (1, '{"studioName":"Pilates Studio","logoData":null,"colorTheme":"#7c3aed","numInstructors":7,"classTypes":{"mat":true,"reformer":true},"defaultDuration":60,"timeSlots":["Morning","Afternoon","Evening"],"paymentTypes":{"cash":true,"upi":true,"card":false},"currency":"INR","packages":[{"id":"p1","name":"Starter","classes":4,"price":1999},{"id":"p2","name":"Regular","classes":8,"price":3499},{"id":"p3","name":"Unlimited","classes":999,"price":5999}],"demoSessions":1,"instructorName":"Priya Sharma","instructorSpecialization":"Mat & Reformer","instructorPhoto":null,"sidebarBg":"#1a1a2e","sidebarText":"#9ca3af","sidebarActiveBg":"rgba(124,58,237,0.2)","sidebarActiveText":"#a78bfa","sidebarHoverBg":"rgba(255,255,255,0.06)","sidebarBannerData":null,"sidebarBannerText":"","ai":{"enabled":false,"baseUrl":"https://api.openai.com/v1","apiKey":"","model":"gpt-4o-mini","temperature":0.4}}');

-- instructors
INSERT INTO public.instructors (id, name, specialization, certification, experience, email, phone, photo, active, date_joined, bio, availability, permissions, rating, login_id) VALUES ('i1', 'Priya Sharma', 'Mat & Reformer', 'ACE Certified Personal Trainer', 8, 'priya@zenpilates.com', '+91 98765 43201', NULL, true, '2026-01-15', 'Certified Pilates instructor with 8+ years experience. Specializes in gentle flows for beginners.', '{"mon":["07:00","09:00","11:00"],"tue":["07:00","09:00"],"wed":["07:00","09:00","11:00"],"thu":["07:00","09:00"],"fri":["07:00","09:00","11:00"]}', '{"editSchedule":true,"editPricing":false}', 4.6, NULL);
INSERT INTO public.instructors (id, name, specialization, certification, experience, email, phone, photo, active, date_joined, bio, availability, permissions, rating, login_id) VALUES ('i2', 'Amit Patel', 'Reformer, Rehab', 'Pilates Method Alliance Certified', 6, 'amit@zenpilates.com', '+91 98765 43202', NULL, true, '2026-03-01', 'Advanced Reformer specialist. Trained in classical and contemporary Pilates methods.', '{"mon":["09:00","11:00"],"tue":["09:00","11:00"],"wed":["09:00"],"thu":["09:00","11:00"],"fri":["09:00","11:00"]}', '{"editSchedule":true,"editPricing":false}', 4.3, NULL);
INSERT INTO public.instructors (id, name, specialization, certification, experience, email, phone, photo, active, date_joined, bio, availability, permissions, rating, login_id) VALUES ('i3', 'Sneha Kapoor', 'Mat Pilates, Pre/Postnatal', 'NASM-CPT, Pilates Mat Specialist', 5, 'sneha@zenpilates.com', '+91 98765 43203', NULL, true, '2026-04-10', 'Expert mat instructor. Focus on core strength, flexibility, and mindful movement.', '{"mon":["07:00","17:00"],"wed":["07:00","17:00"],"fri":["07:00","17:00"]}', '{"editSchedule":true,"editPricing":false}', 4.8, NULL);
INSERT INTO public.instructors (id, name, specialization, certification, experience, email, phone, photo, active, date_joined, bio, availability, permissions, rating, login_id) VALUES ('i4', 'Vikram Raj', 'Mat, Hatha Yoga', 'E-RYT 500, Yoga Alliance', 4, 'vikram@zenpilates.com', '+91 98765 43204', NULL, false, '2026-02-20', 'Hatha Yoga and Mat Pilates fusion instructor on sabbatical.', '{"mon":["07:00"],"wed":["07:00"],"fri":["07:00"]}', '{"editSchedule":false,"editPricing":false}', 4.1, NULL);
INSERT INTO public.instructors (id, name, specialization, certification, experience, email, phone, photo, active, date_joined, bio, availability, permissions, rating, login_id) VALUES ('i5', 'Ritu Agarwal', 'Reformer, Pilates Sculpt', 'ACE, Balanced Body Reformer Certified', 3, 'ritu@zenpilates.com', '+91 98765 43205', NULL, true, '2026-05-01', 'Energetic reformer instructor who loves high-intensity Pilates sculpt classes.', '{"mon":["17:00","18:00"],"tue":["17:00"],"wed":["17:00","18:00"],"thu":["17:00"],"fri":["17:00","18:00"]}', '{"editSchedule":true,"editPricing":true}', 4, NULL);
INSERT INTO public.instructors (id, name, specialization, certification, experience, email, phone, photo, active, date_joined, bio, availability, permissions, rating, login_id) VALUES ('i6', 'Deepa Menon', 'Pre/Postnatal, Mat, Restorative', 'Polestar Pilates, Prenatal Specialist', 7, 'deepa@zenpilates.com', '+91 98765 43206', NULL, true, '2025-11-01', 'Gentle restorative and prenatal Pilates specialist. Creates a safe space for all bodies.', '{"mon":["07:00","08:00","09:00"],"tue":["07:00","08:00"],"wed":["07:00","08:00","09:00"],"thu":["07:00","08:00"],"fri":["07:00","08:00","09:00"]}', '{"editSchedule":true,"editPricing":false}', 4.9, NULL);
INSERT INTO public.instructors (id, name, specialization, certification, experience, email, phone, photo, active, date_joined, bio, availability, permissions, rating, login_id) VALUES ('neelamr', 'Neelam R', 'Mat & Reformer', 'PMA Certified, Mat & Reformer Specialist', 7, 'neelamr@zenpilates.com', '+91 98765 43207', NULL, true, '2024-09-01', 'Lead instructor with 7+ years experience. Known for energetic morning flows and mindful cueing.', '{"mon":["07:00","09:00"],"tue":["07:00","09:00"],"wed":["07:00","09:00"],"thu":["07:00","09:00"],"fri":["07:00","09:00"]}', '{"editSchedule":true,"editPricing":true}', 4.8, 'neelamr');

-- students
INSERT INTO public.students (id, name, phone, email, gender, emergency, active, level, level_progress, enrolled_classes, enrolled_demos) VALUES ('s1', 'Neha Sharma', '+91 98765 43210', 'neha@email.com', 'Female', '+91 98765 43211', true, 'intermediate', '{"beginner":12,"intermediate":5,"expert":0}', '{"c11","c13","c14","c15","c1","c5","c6","c7","c8","c27","c29","c30"}'::text[], '{}'::text[]);
INSERT INTO public.students (id, name, phone, email, gender, emergency, active, level, level_progress, enrolled_classes, enrolled_demos) VALUES ('s2', 'Kavita Singh', '+91 98765 43212', 'kavita@email.com', 'Female', '', true, 'beginner', '{"beginner":5,"intermediate":0,"expert":0}', '{"c11","c13","c15","c1","c6","c7","c27","c29"}'::text[], '{}'::text[]);
INSERT INTO public.students (id, name, phone, email, gender, emergency, active, level, level_progress, enrolled_classes, enrolled_demos) VALUES ('s3', 'Meera Iyer', '+91 98765 43213', 'meera@email.com', 'Female', '', true, 'beginner', '{"beginner":3,"intermediate":0,"expert":0}', '{"c11","c13","c15","c1","c6","c7","c27","c29"}'::text[], '{}'::text[]);
INSERT INTO public.students (id, name, phone, email, gender, emergency, active, level, level_progress, enrolled_classes, enrolled_demos) VALUES ('s4', 'Rohit Joshi', '+91 98765 43214', 'rohit@email.com', 'Male', '', true, 'intermediate', '{"beginner":10,"intermediate":4,"expert":0}', '{"c11","c12","c13","c15","c2","c6","c7","c8","c27","c28","c29"}'::text[], '{}'::text[]);
INSERT INTO public.students (id, name, phone, email, gender, emergency, active, level, level_progress, enrolled_classes, enrolled_demos) VALUES ('s5', 'Ananya K.', '+91 98765 43215', 'ananya@email.com', 'Female', '', true, 'beginner', '{"beginner":2,"intermediate":0,"expert":0}', '{"c11","c15","c6","c27"}'::text[], '{"d1"}'::text[]);
INSERT INTO public.students (id, name, phone, email, gender, emergency, active, level, level_progress, enrolled_classes, enrolled_demos) VALUES ('s6', 'Priya Mehta', '+91 98765 43216', 'priyam@email.com', 'Female', '', true, 'beginner', '{"beginner":4,"intermediate":0,"expert":0}', '{"c12","c15","c16","c2","c8","c28"}'::text[], '{}'::text[]);
INSERT INTO public.students (id, name, phone, email, gender, emergency, active, level, level_progress, enrolled_classes, enrolled_demos) VALUES ('s7', 'Amit Patel', '+91 98765 43217', 'amitp@email.com', 'Male', '', true, 'expert', '{"beginner":15,"intermediate":12,"expert":9}', '{"c12","c14","c16","c2","c8","c28","c30"}'::text[], '{}'::text[]);
INSERT INTO public.students (id, name, phone, email, gender, emergency, active, level, level_progress, enrolled_classes, enrolled_demos) VALUES ('s8', 'Sneha Reddy', '+91 98765 43218', 'sneha@email.com', 'Female', '', true, 'beginner', '{"beginner":2,"intermediate":0,"expert":0}', '{"c15","c22","c25","c26"}'::text[], '{}'::text[]);
INSERT INTO public.students (id, name, phone, email, gender, emergency, active, level, level_progress, enrolled_classes, enrolled_demos) VALUES ('s9', 'Neelam Varma', '+91 98765 43219', 'neelam@email.com', 'Female', '', true, 'expert', '{"beginner":15,"intermediate":14,"expert":12}', '{"c2","c8","c11","c12","c14","c16","c5","c10","c20","c28","c30"}'::text[], '{}'::text[]);

-- classes
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c11', 'mat', 'beginner', '2026-06-10', '07:00', 60, 15, 'active', 'i1', '{"s1","s2","s3","s4","s5","s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c12', 'reformer', 'intermediate', '2026-06-12', '09:00', 60, 10, 'active', 'i2', '{"s4","s6","s7","s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c13', 'mat', 'intermediate', '2026-06-15', '17:00', 45, 15, 'active', 'i1', '{"s1","s2","s3","s4"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c14', 'reformer', 'expert', '2026-06-18', '09:00', 60, 10, 'active', 'i2', '{"s1","s7","s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c15', 'mat', 'beginner', '2026-06-22', '07:00', 60, 15, 'active', 'i1', '{"s1","s2","s3","s4","s5","s6"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c16', 'reformer', 'beginner', '2026-06-25', '09:00', 60, 10, 'active', 'i2', '{"s6","s7","s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c1', 'mat', 'beginner', '2026-07-04', '07:00', 60, 15, 'active', 'i1', '{"s1","s2","s3","s4","s5"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c2', 'reformer', 'intermediate', '2026-07-04', '09:00', 60, 10, 'active', 'i2', '{"s4","s6","s7","s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c3', 'mat', 'beginner', '2026-07-04', '17:00', 45, 15, 'active', 'i1', '{"s1","s2","s3"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c4', 'mat', 'beginner', '2026-07-07', '07:00', 60, 15, 'active', 'i1', '{}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c5', 'reformer', 'expert', '2026-07-08', '09:00', 60, 10, 'active', 'i2', '{"s1","s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c6', 'mat', 'beginner', '2026-07-10', '07:00', 60, 15, 'active', 'i1', '{"s1","s2","s3","s4","s5"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c7', 'mat', 'beginner', '2026-07-13', '07:00', 60, 15, 'active', 'i1', '{"s1","s2","s3","s4"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c8', 'reformer', 'intermediate', '2026-07-15', '09:00', 60, 10, 'active', 'i2', '{"s4","s6","s7","s1","s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c9', 'mat', 'beginner', '2026-07-17', '17:00', 45, 15, 'active', 'i1', '{}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c10', 'reformer', 'expert', '2026-07-20', '09:00', 60, 10, 'active', 'i2', '{"s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c17', 'mat', 'intermediate', '2026-07-22', '07:00', 60, 15, 'active', 'i1', '{"s1","s4"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c18', 'reformer', 'beginner', '2026-07-24', '09:00', 60, 10, 'active', 'i2', '{"s6"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c19', 'mat', 'beginner', '2026-07-27', '07:00', 60, 15, 'active', 'i1', '{}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c20', 'reformer', 'expert', '2026-07-29', '09:00', 60, 10, 'active', 'i2', '{"s7","s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c21', 'mat', 'beginner', '2026-07-05', '08:00', 45, 12, 'active', 'i3', '{"s2","s3","s5"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c22', 'mat', 'beginner', '2026-07-12', '08:00', 45, 12, 'active', 'i3', '{"s2","s8"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c23', 'reformer', 'beginner', '2026-07-06', '17:00', 60, 8, 'active', 'i5', '{"s5","s6"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c24', 'reformer', 'intermediate', '2026-07-14', '17:00', 60, 8, 'active', 'i5', '{"s4"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c25', 'mat', 'beginner', '2026-07-06', '07:00', 60, 10, 'active', 'i6', '{"s1","s3","s8"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c26', 'mat', 'beginner', '2026-07-13', '07:00', 60, 10, 'active', 'i6', '{"s2","s5","s6","s8"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c27', 'mat', 'beginner', '2026-08-10', '07:00', 60, 15, 'active', 'neelamr', '{"s1","s2","s3","s4","s5"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c28', 'reformer', 'intermediate', '2026-08-10', '09:00', 60, 10, 'active', 'neelamr', '{"s4","s6","s7","s9"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c29', 'mat', 'beginner', '2026-08-11', '07:00', 60, 15, 'active', 'neelamr', '{"s1","s2","s3","s4"}'::text[], '{}'::text[]);
INSERT INTO public.classes (id, type, level, date, time, duration, max_students, status, instructor, enrolled, waitlist) VALUES ('c30', 'reformer', 'expert', '2026-08-11', '09:00', 60, 10, 'active', 'neelamr', '{"s1","s7","s9"}'::text[], '{}'::text[]);

-- demo sessions
INSERT INTO public.demo_sessions (id, date, time, duration, max_students, enrolled) VALUES ('d1', '2026-08-10', '17:00', 45, 5, '{"s5"}'::text[]);
INSERT INTO public.demo_sessions (id, date, time, duration, max_students, enrolled) VALUES ('d2', '2026-08-11', '07:00', 45, 5, '{}'::text[]);
INSERT INTO public.demo_sessions (id, date, time, duration, max_students, enrolled) VALUES ('d3', '2026-08-11', '09:00', 45, 5, '{}'::text[]);

-- attendance
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c11', 's1', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c11', 's2', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c11', 's3', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c11', 's4', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c11', 's5', 'late');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c11', 's9', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c12', 's4', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c12', 's6', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c12', 's7', 'absent');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c12', 's9', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c13', 's1', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c13', 's2', 'late');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c13', 's3', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c13', 's4', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c14', 's1', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c14', 's7', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c14', 's9', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c15', 's1', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c15', 's2', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c15', 's3', 'absent');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c15', 's4', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c15', 's5', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c15', 's6', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c16', 's6', 'late');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c16', 's7', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c16', 's9', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c1', 's1', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c1', 's2', 'absent');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c1', 's3', 'late');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c1', 's4', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c1', 's5', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c6', 's1', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c6', 's2', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c6', 's3', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c6', 's4', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c6', 's5', 'late');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c7', 's1', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c7', 's2', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c7', 's3', 'late');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c7', 's4', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c8', 's1', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c8', 's4', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c8', 's6', 'late');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c8', 's7', 'present');
INSERT INTO public.attendance (class_id, student_id, status) VALUES ('c8', 's9', 'present');

-- class notes
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c11', 's1', 'Strong form today, excellent core control', '{"Form"}'::text[], '2026-06-10T07:45:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c11', 's1', 'Remind about breathing during rollout', '{"Breathing"}'::text[], '2026-06-10T07:30:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c11', 's2', 'Needs work on hip alignment', '{"Form"}'::text[], '2026-06-10T07:40:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c11', 's3', 'Great energy, focus on even weight distribution', '{"Core","Form"}'::text[], '2026-06-10T07:35:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c11', 's5', 'Arrived 5min late but caught up well', '{"Motivation"}'::text[], '2026-06-10T07:50:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c11', 's9', 'Outstanding form today, leading the class through warm-up', '{"Form","Motivation"}'::text[], '2026-06-10T07:40:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c12', 's4', 'Excellent reformer technique, progressing well', '{"Form","Core"}'::text[], '2026-06-12T09:45:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c12', 's6', 'First time on reformer, needs confidence', '{"Breathing","Form"}'::text[], '2026-06-12T09:30:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c12', 's9', 'Effortless reformer transitions, natural talent', '{"Core","Form"}'::text[], '2026-06-12T09:50:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c13', 's1', 'Core engagement improving steadily', '{"Core"}'::text[], '2026-06-15T17:40:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c13', 's2', 'Late again, disrupted warm-up', '{"Motivation"}'::text[], '2026-06-15T17:45:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c13', 's4', 'Great to see you at mat class too!', '{"Motivation"}'::text[], '2026-06-15T17:35:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c14', 's1', 'Handled expert-level flow with confidence', '{"Form","Core"}'::text[], '2026-06-18T09:50:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c14', 's7', 'Excellent teaser, inspiring the class', '{"Form","Motivation"}'::text[], '2026-06-18T09:40:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c14', 's9', 'Mastered the advanced flow, assisting others with modifications', '{"Motivation","Form"}'::text[], '2026-06-18T09:45:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c15', 's1', 'Consistent performer, helping newer students', '{"Motivation","Form"}'::text[], '2026-06-22T07:50:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c15', 's2', 'Much better posture today', '{"Posture"}'::text[], '2026-06-22T07:40:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c15', 's4', 'Watch knee alignment in lunges', '{"Injury","Form"}'::text[], '2026-06-22T07:45:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c15', 's5', 'First mat class, great enthusiasm', '{"Motivation"}'::text[], '2026-06-22T07:30:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c15', 's6', 'Keep breathing steady during holds', '{"Breathing"}'::text[], '2026-06-22T07:35:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c16', 's6', 'Reformer coming along, focus on footwork', '{"Form"}'::text[], '2026-06-25T09:30:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c16', 's7', 'Helped demonstrate for newer student', '{"Motivation"}'::text[], '2026-06-25T09:45:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c16', 's9', 'Flawless footwork series, great example for class', '{"Form","Motivation"}'::text[], '2026-06-25T09:50:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c1', 's1', 'Great energy today, leading the warm-up flow', '{"Motivation","Form"}'::text[], '2026-07-04T07:10:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c1', 's1', 'Excellent core engagement during roll-ups', '{"Core"}'::text[], '2026-07-04T07:25:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c1', 's2', 'Marked absent - notified via SMS', '{"Motivation"}'::text[], '2026-07-04T07:05:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c1', 's3', 'Arrived late but warmed up quickly', '{"Motivation"}'::text[], '2026-07-04T07:15:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c1', 's3', 'Remind to breathe during hamstring stretches', '{"Breathing"}'::text[], '2026-07-04T07:30:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c1', 's4', 'Strong reformer transitions, watch lower back', '{"Form","Injury"}'::text[], '2026-07-04T07:20:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c1', 's5', 'First mat class, needs extra spotting on roll-over', '{"Form"}'::text[], '2026-07-04T07:22:00');
INSERT INTO public.class_notes (class_id, student_id, text, tags, created_at) VALUES ('c8', 's9', 'Exceptional control on the reformer, demonstrating advanced variations', '{"Form","Core"}'::text[], '2026-07-15T09:35:00');

-- student notes
INSERT INTO public.student_notes (id, student_id, text, date, added_by) VALUES ('n1', 's1', 'Making excellent progress, ready for more advanced work', '2026-06-20', 'Priya Sharma');
INSERT INTO public.student_notes (id, student_id, text, date, added_by) VALUES ('n2', 's2', 'Encourage to arrive on time, punctuality improving', '2026-06-18', 'Priya Sharma');
INSERT INTO public.student_notes (id, student_id, text, date, added_by) VALUES ('n3', 's4', 'Great all-rounder, attending both mat and reformer', '2026-06-22', 'Amit Patel');
INSERT INTO public.student_notes (id, student_id, text, date, added_by) VALUES ('n4', 's6', 'New student, very motivated, learning fast', '2026-06-20', 'Amit Patel');
INSERT INTO public.student_notes (id, student_id, text, date, added_by) VALUES ('n5', 's3', 'Wrist injury resolved, back to full practice', '2026-06-25', 'Priya Sharma');
INSERT INTO public.student_notes (id, student_id, text, date, added_by) VALUES ('n6', 's5', 'Consistent attendance in June, great foundation building', '2026-06-25', 'Priya Sharma');
INSERT INTO public.student_notes (id, student_id, text, date, added_by) VALUES ('n7', 's9', 'Star performer — exceptional form and dedication across all levels', '2026-06-25', 'Amit Patel');
INSERT INTO public.student_notes (id, student_id, text, date, added_by) VALUES ('n8', 's9', 'Neelam is ready to assist with beginner classes as a peer mentor', '2026-06-22', 'Amit Patel');

-- milestones
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m1', 's1', 'Held plank for 60s', 'Achieved full 60-second plank with proper form.', '2026-06-20', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m2', 's1', 'Advanced to Intermediate', 'Completed 5+ Beginner classes with excellent attendance.', '2026-06-25', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m3', 's4', 'First Reformer class', 'Completed first reformer class with good form.', '2026-06-10', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m4', 's7', 'Mastered Teaser', 'Successfully executed Teaser without modifications.', '2026-06-15', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m5', 's1', 'Perfect Attendance - June', 'Attended every June class without absence.', '2026-06-25', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m6', 's6', 'First Week Complete', 'Completed first full week of Pilates classes.', '2026-06-20', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m7', 's2', 'Core strength improvement', 'Notable improvement in core engagement during June.', '2026-06-22', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m8', 's4', 'Reformer Foundation', 'Completed Reformer foundation course.', '2026-06-18', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m9', 's5', 'First Month Milestone', 'Completed first month of consistent practice.', '2026-06-25', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m10', 's9', 'Advanced to Expert Level', 'Completed 10+ Intermediate classes with distinction.', '2026-06-20', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m11', 's9', 'Perfect Attendance Record', 'Zero absences across 12 consecutive classes.', '2026-06-25', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m12', 's9', 'Reformer Pro', 'Demonstrated mastery of all reformer exercises.', '2026-06-22', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m13', 's9', 'Peer Mentor', 'Started assisting newer students during classes.', '2026-06-18', true);
INSERT INTO public.student_milestones (id, student_id, title, description, date, achieved) VALUES ('m14', 's9', '100 Classes Milestone', 'Completed 100 Pilates classes at the studio.', '2026-06-25', true);

-- injuries
INSERT INTO public.student_injuries (id, student_id, body_part, severity, notes, modification, date, resolved) VALUES ('inj1', 's1', 'Lower Back', 'mild', 'Mild strain from gardening, avoid deep backbends', 'Use neutral spine, avoid Cobra, substitute Childs Pose', '2026-06-10', false);
INSERT INTO public.student_injuries (id, student_id, body_part, severity, notes, modification, date, resolved) VALUES ('inj2', 's3', 'Right Wrist', 'moderate', 'Carpal tunnel flare-up from desk work', 'Use fists for planks, skip Chaturanga, use wrist support', '2026-06-05', true);
INSERT INTO public.student_injuries (id, student_id, body_part, severity, notes, modification, date, resolved) VALUES ('inj3', 's4', 'Left Knee', 'mild', 'Old sports injury acting up', 'Avoid deep lunges, modify warriors', '2026-06-15', false);

-- instructor feedback
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i1', 's1', 5, 'Priya is amazing! Very patient and explains each move perfectly.', '2026-06-20');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i1', 's2', 4, 'Great beginner class, felt very comfortable.', '2026-06-18');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i1', 's4', 5, 'Best instructor for mat Pilates. Highly recommend!', '2026-06-22');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i1', 's3', 4, 'Very clear instructions and good pace for beginners.', '2026-06-19');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i1', 's5', 5, 'Priya makes every class fun and challenging!', '2026-06-25');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i2', 's4', 4, 'Challenging reformer class but very rewarding.', '2026-06-19');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i2', 's7', 5, 'Amit pushes you to your limits safely. Expert-level guidance.', '2026-06-21');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i2', 's1', 4, 'Great reformer session. Felt the burn!', '2026-06-22');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i3', 's1', 5, 'Sneha''s mat class transformed my core strength.', '2026-06-17');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i3', 's3', 5, 'Loved the prenatal modifications. So thoughtful!', '2026-06-23');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i5', 's5', 4, 'Ritu''s sculpt class is intense but rewarding!', '2026-07-02');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i5', 's6', 3, 'Good class but moved a bit fast for me.', '2026-07-02');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i6', 's1', 5, 'Deepa is so calming. Her restorative class is exactly what I needed.', '2026-07-01');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i6', 's3', 5, 'Best prenatal class in town. Deepa is amazing!', '2026-07-01');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i6', 's8', 4, 'Very welcoming atmosphere for beginners.', '2026-07-03');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i2', 's9', 5, 'Neelam is one of the most dedicated students I have ever taught. Exceptional!', '2026-06-22');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i1', 's9', 5, 'A natural leader in class. Other students look up to her.', '2026-06-20');
INSERT INTO public.instructor_feedback (instructor_id, student_id, rating, comment, date) VALUES ('i2', 's9', 5, 'Outstanding progress — went from intermediate to expert in record time.', '2026-06-25');

COMMIT;
